baseURL = 'https://404unfound.com/'
languageCode = 'en-us'
title = '404Unfound'
theme = "hugo-theme-monochrome"
pagination.pagerSize = 5
enableEmoji = true

[minify]
disableXML = true
minifyOutput = true

[markup.highlight]
codeFences = false
lineNos = false

[params]
footer = "© 2024 <a href=\"https://404unfound.com/\">404Unfound</a> Powered by <a href=\"https://gohugo.io/\">Hugo</a> & <a href=\"https://github.com/kaiiiz/hugo-theme-monochrome\">Monochrome</a>"
enable_toc = false
color_scheme = "dark"
enable_site_search = true

[params.syntax_highlight]
lib = "prism.js"

[params.syntax_highlight.prism]
enable_line_no = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
ctf = "CTFs"
authors = "authors"

[[menu.navbar]]
identifier = "Writeups"
name = "Writeups"
title = "Writeups"
url = "/writeups"
weight = 1

[[menu.navbar]]
identifier = "Members"
name = "Members"
url = "/members"
weight = 2

[[menu.navbar]]
identifier = "Tags"
name = "Tags"
title = "Tags"
url = "/tags"
weight = 3

[[menu.navbar]]
identifier = "CTFs"
name = "CTFs"
title = "CTFs"
url = "/ctfs"
weight = 4

[[menu.navbar]]
identifier = "Authors"
name = "Authors"
url = "/authors"
weight = 5
