baseURL = '/'
languageCode = 'en-us'
title = '404Unfound'
theme = "hugo-theme-monochrome"
paginate = 5
enableEmoji = true

[minify]
disableXML = true
minifyOutput = true

[markup.highlight]
codeFences = false
lineNos = false

[params]
footer = "Copyright © 2023 by <a href=\"https://404unfound.com/\">404Unfound</a>"
enable_toc = false
color_scheme = "dark"
enable_site_search = true

[params.syntax_highlight]
lib = "prism.js"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
ctf = "CTFs"

[[menu.navbar]]
identifier = "Writeups"
name = "Writeups"
title = "Writeups"
url = "/writeups"
weight = 1

[[menu.navbar]]
identifier = "Tags"
name = "Tags"
title = "Tags"
url = "/tags"
weight = 2

[[menu.navbar]]
identifier = "CTFs"
name = "CTFs"
title = "CTFs"
url = "/ctfs"
weight = 3

[[menu.navbar]]
identifier = "Members"
name = "Members"
url = "/members"
weight = 4

