[[navbar]]
  identifier = "setup"
  name = "Setup"
  url = "/setup/"
  weight = 1
[[navbar]]
  identifier = "changelog"
  name = "Changelog"
  url = "/changelog/"
  weight = 2
[[navbar]]
  identifier = "configuration"
  name = "Configuration"
  url = "/configuration/"
  weight = 3
  [[navbar]]
    identifier = "site_settings"
    name = "Site Settings"
    url = "/configuration/site"
    parent = "configuration"
    weight = 1
  [[navbar]]
    identifier = "theme_settings"
    name = "Theme Settings"
    url = "/configuration/theme"
    parent = "configuration"
    weight = 2
  [[navbar]]
    identifier = "page_settings"
    name = "Page Settings"
    url = "/configuration/page"
    parent = "configuration"
    weight = 3
[[navbar]]
  identifier = "layouts"
  name = "Layouts"
  url = "/layouts/"
  weight = 4
  [[navbar]]
    identifier = "balloon"
    name = "Balloon"
    url = "/layouts/balloon"
    parent = "layouts"
    [[navbar]]
      identifier = "balloon_demo"
      name = "Demo"
      url = "/layouts/balloon/demo"
      parent = "balloon"
      weight = 1
    [[navbar]]
      identifier = "balloon_docs"
      name = "Document"
      url = "/layouts/balloon/docs"
      parent = "balloon"
      weight = 2
  [[navbar]]
    identifier = "bookcase"
    name = "Bookcase"
    url = "/layouts/bookcase"
    parent = "layouts"
    [[navbar]]
      identifier = "bookcase_demo"
      name = "Demo"
      url = "/layouts/bookcase/demo"
      parent = "bookcase"
      weight = 1
    [[navbar]]
      identifier = "bookcase_docs"
      name = "Document"
      url = "/layouts/bookcase/docs"
      parent = "bookcase"
      weight = 2
  [[navbar]]
    identifier = "gallery"
    name = "Gallery"
    url = "/layouts/gallery"
    parent = "layouts"
    [[navbar]]
      identifier = "gallery_demo"
      name = "Demo"
      url = "/layouts/gallery/demo"
      parent = "gallery"
      weight = 1
    [[navbar]]
      identifier = "gallery_docs"
      name = "Document"
      url = "/layouts/gallery/docs"
      parent = "gallery"
      weight = 2
  [[navbar]]
    identifier = "list"
    name = "List"
    url = "/layouts/list"
    parent = "layouts"
    [[navbar]]
      identifier = "list_demo"
      name = "Demo"
      url = "/layouts/list/demo"
      parent = "list"
      weight = 1
    [[navbar]]
      identifier = "list_docs"
      name = "Document"
      url = "/layouts/list/docs"
      parent = "list"
      weight = 2
  [[navbar]]
    identifier = "postcard"
    name = "Postcard"
    url = "/layouts/postcard"
    parent = "layouts"
    [[navbar]]
      identifier = "postcard_demo"
      name = "Demo"
      url = "/layouts/postcard/demo"
      parent = "postcard"
      weight = 1
    [[navbar]]
      identifier = "postcard_docs"
      name = "Document"
      url = "/layouts/postcard/docs"
      parent = "postcard"
      weight = 2
  [[navbar]]
    identifier = "blank"
    name = "Blank"
    url = "/layouts/blank"
    parent = "layouts"
    [[navbar]]
      identifier = "blank_demo"
      name = "Demo"
      url = "/layouts/blank/demo"
      parent = "blank"
      weight = 1
    [[navbar]]
      identifier = "blank_docs"
      name = "Document"
      url = "/layouts/blank/docs"
      parent = "blank"
      weight = 2
[[navbar]]
  identifier = "shortcodes"
  name = "Shortcodes"
  url = "/shortcodes/"
  weight = 5
[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 6
